Code cleanup

diff --git a/munin-plugins/wobble-online-users b/munin-plugins/wobble-online-users
--- a/munin-plugins/wobble-online-users
+++ b/munin-plugins/wobble-online-users
@@ -13,7 +13,12 @@ EOM
         exit 0;;
 esac
 
+if [ -z "$WOBBLE_HOME" ]; then
+  echo "ERROR: No WOBBLE_HOME set."
+  exit 1
+fi
+
 echo -n "users.value "
-/opt/wobble_dev/scripts/get-online-users.php
+$WOBBLE_HOME/scripts/get-online-users.php
 echo -n "sessions.value "
-/opt/wobble_dev/scripts/get-online-users.php --sessions
+$WOBBLE_HOME/scripts/get-online-users.php --sessions
diff --git a/munin-plugins/wobble-warning-sensors b/munin-plugins/wobble-warning-sensors
--- a/munin-plugins/wobble-warning-sensors
+++ b/munin-plugins/wobble-warning-sensors
@@ -13,7 +13,12 @@ EOM
         exit 0;;
 esac
 
+if [ -z "$WOBBLE_HOME" ]; then
+  echo "ERROR: No WOBBLE_HOME set."
+  exit 1
+fi
+
 echo -n "orphaned_topics.value "
-/opt/wobble_dev/scripts/wobble-warning-sensors.php --orphaned-topics
+$WOBBLE_HOME/scripts/wobble-warning-sensors.php --orphaned-topics
 echo -n "orphaned_posts.value "
-/opt/wobble_dev/scripts/wobble-warning-sensors.php
+$WOBBLE_HOME/scripts/wobble-warning-sensors.php --orphaned-posts
